# If on windows, make sure to run with WSL and NOT the windows command line
version: '3.1'
services:
  postgres_db:
    # Alpine image is nearly 50% smaller than Ubuntu
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: alerts
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

# Database will persist after `docker-compose down`
volumes:
  db-data: