ktor {
    deployment {
        port = 8080
    }
    application {
        modules = [ com.example.ApplicationKt.module ]
    }
}

database:
    url: ${DB_URL}
    driver: org.postgresql.Driver
    user: ${DB_USER}
    password: ${DB_PASSWORD}