ktor:
    deployment:
        port: 8080
    application:
        modules:
            - club.awesome.ApplicationKt.module
db:
    url: postgres://postgres.yavstzicdcjbqsvnfhxy:>rmXk2b>NY7J=;V@aws-0-us-west-1.pooler.supabase.com:5432/postgres
    email: "ccobb4974@sdsu.edu"
    pass: ">rmXk2b>NY7J=;V"